import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

import { DatabaseNotFoundError } from '@/lib/db/errors';
import { getPublicReportVerification } from '@/lib/services/report-verification.service';

export const metadata: Metadata = {
  title: 'Verify NAWI Test Report',
  description: 'Public verification of a report generated by the NAWI R76 testing platform.',
};

function display(value: string): string { return value.replaceAll('_', ' '); }
function date(value: string | null): string {
  if (!value) return 'Not recorded';
  return new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' }).format(new Date(value)) + ' UTC';
}

export default async function VerifyReportPage({ params }: { params: Promise<{ qrVerificationId: string }> }) {
  const { qrVerificationId } = await params;
  let report;
  try {
    report = await getPublicReportVerification(qrVerificationId.trim());
  } catch (error) {
    if (error instanceof DatabaseNotFoundError) notFound();
    throw error;
  }

  const title = report.status === 'VERIFIED' ? 'Verified Report' : report.status === 'REVOKED' ? 'Report Revoked' : 'Report Not Valid';
  const validTone = report.status === 'VERIFIED';

  return (
    <main className="min-h-screen bg-[#F7F9FB] px-4 py-8 sm:px-6">
      <div className="mx-auto max-w-3xl">
        <header className="mb-5 flex items-center gap-3 border-b border-[#D9E2EC] bg-white px-5 py-4">
          <div className="flex h-10 w-10 items-center justify-center rounded bg-[#0A66C2] text-lg font-bold text-white">R76</div>
          <div><p className="m-0 text-[0.92rem] font-bold text-[#1D2226]">NAWI Report Verification</p><p className="m-0 mt-0.5 text-[0.68rem] text-[#667085]">Public verification record</p></div>
        </header>
        <section className={`overflow-hidden rounded-lg border bg-white shadow-[0_1px_3px_rgba(16,24,40,0.08)] ${validTone ? 'border-[#ABEFC6]' : 'border-[#FDA29B]'}`}>
          <div className={`px-6 py-5 ${validTone ? 'bg-[#ECFDF3]' : 'bg-[#FEF3F2]'}`}>
            <p className={`m-0 text-[0.64rem] font-bold uppercase tracking-[0.12em] ${validTone ? 'text-[#067647]' : 'text-[#B42318]'}`}>{display(report.status)}</p>
            <h1 className={`m-0 mt-1 text-2xl font-bold ${validTone ? 'text-[#065F46]' : 'text-[#991B1B]'}`}>{title}</h1>
            <p className="m-0 mt-2 text-[0.76rem] leading-relaxed text-[#475467]">This record matches a report generated by this NAWI testing platform from an approved test session.</p>
          </div>
          <div className="grid gap-6 p-6">
            <section><h2 className="m-0 border-b border-[#D9E2EC] pb-2 text-[0.72rem] font-bold uppercase tracking-[0.09em] text-[#344054]">Report</h2><dl className="mt-3 grid grid-cols-1 gap-3 text-[0.75rem] sm:grid-cols-2"><div><dt className="text-[#667085]">Reference</dt><dd className="m-0 mt-0.5 font-bold text-[#1D2226]">{report.reportReference}</dd></div><div><dt className="text-[#667085]">Version</dt><dd className="m-0 mt-0.5 font-semibold">{report.reportVersion}</dd></div><div><dt className="text-[#667085]">Generated</dt><dd className="m-0 mt-0.5 font-semibold">{date(report.issuedAt)}</dd></div><div><dt className="text-[#667085]">Final approval</dt><dd className="m-0 mt-0.5 font-semibold">{date(report.finalApprovalAt)}</dd></div></dl></section>
            <section><h2 className="m-0 border-b border-[#D9E2EC] pb-2 text-[0.72rem] font-bold uppercase tracking-[0.09em] text-[#344054]">Instrument</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-[0.75rem] sm:grid-cols-3"><div><dt className="text-[#667085]">Manufacturer</dt><dd className="m-0 mt-0.5 font-semibold">{report.manufacturer}</dd></div><div><dt className="text-[#667085]">Model</dt><dd className="m-0 mt-0.5 font-semibold">{report.model}</dd></div><div><dt className="text-[#667085]">Type</dt><dd className="m-0 mt-0.5 font-semibold">{display(report.instrumentType)}</dd></div><div><dt className="text-[#667085]">Accuracy class</dt><dd className="m-0 mt-0.5 font-semibold">{report.accuracyClass}</dd></div><div><dt className="text-[#667085]">Max / Min</dt><dd className="m-0 mt-0.5 font-semibold">{report.max} / {report.min} kg</dd></div><div><dt className="text-[#667085]">e / d</dt><dd className="m-0 mt-0.5 font-semibold">{report.e} / {report.d} kg</dd></div></dl></section>
            <section><h2 className="m-0 border-b border-[#D9E2EC] pb-2 text-[0.72rem] font-bold uppercase tracking-[0.09em] text-[#344054]">Decision</h2><dl className="mt-3 grid grid-cols-1 gap-3 text-[0.75rem] sm:grid-cols-3"><div><dt className="text-[#667085]">Ruleset</dt><dd className="m-0 mt-0.5 font-semibold">{report.ruleset}</dd></div><div><dt className="text-[#667085]">Persisted compliance result</dt><dd className="m-0 mt-0.5 font-bold">{display(report.complianceResult)}</dd></div><div><dt className="text-[#667085]">Approval status</dt><dd className="m-0 mt-0.5 font-bold">{display(report.approvalStatus)}</dd></div></dl></section>
          </div>
          <footer className="border-t border-[#D9E2EC] bg-[#FBFCFD] px-6 py-3 text-[0.66rem] leading-relaxed text-[#667085]">This platform verification does not state or imply that OIML issued or certified the report.</footer>
        </section>
      </div>
    </main>
  );
}
